// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slices

// ConvertInt64ToInterface generics helper.
func ConvertInt64ToInterface(src []int64) []interface{} {
	dst := make([]interface{}, len(src))
	for i, value := range src {
		dst[i] = value
	}
	return dst
}

// AppendInt64ToInterface generics helper.
func AppendInt64ToInterface(dst []interface{}, src ...int64) []interface{} {
	for _, value := range src {
		dst = append(dst, value)
	}
	return dst
}
