// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slices

// ConvertIntToInterface generics helper.
func ConvertIntToInterface(src []int) []interface{} {
	dst := make([]interface{}, len(src))
	for i, value := range src {
		dst[i] = value
	}
	return dst
}

// AppendIntToInterface generics helper.
func AppendIntToInterface(dst []interface{}, src ...int) []interface{} {
	for _, value := range src {
		dst = append(dst, value)
	}
	return dst
}
