// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slices

// ConvertInt64ToAny generics helper.
func ConvertInt64ToAny(src []int64) []any {
	dst := make([]any, len(src))
	for i, value := range src {
		dst[i] = value
	}
	return dst
}

// AppendInt64ToAny generics helper.
func AppendInt64ToAny(dst []any, src ...int64) []any {
	for _, value := range src {
		dst = append(dst, value)
	}
	return dst
}
