// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slices

// ConvertUint64ToAny generics helper.
func ConvertUint64ToAny(src []uint64) []any {
	dst := make([]any, len(src))
	for i, value := range src {
		dst[i] = value
	}
	return dst
}

// AppendUint64ToAny generics helper.
func AppendUint64ToAny(dst []any, src ...uint64) []any {
	for _, value := range src {
		dst = append(dst, value)
	}
	return dst
}
