// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package slices

// SplitInt splits a slice into parts of a given length, with a remainder if necessary.
func SplitInt(src []int, partLen int) [][]int {
	srcLen := len(src)
	if srcLen == 0 {
		return nil
	}
	var dst [][]int
	for a := 0; a < srcLen; a += partLen {
		z := a + partLen
		if z > srcLen {
			z = srcLen
		}
		dst = append(dst, src[a:z])
	}
	return dst
}
