services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: sekret
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - local

networks:
  local:
    driver: bridge
